<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="cod_extract_test" duration-ms="1499" started-at="2018-01-07T17:11:09Z" finished-at="2018-01-07T17:11:11Z">
    <groups>
      <group name="cucumber">
        <method signature="AbstractTestNGCucumberTests.feature(cucumber.api.testng.CucumberFeatureWrapper)[pri:0, instance:cod.extract.test.scripts.DBTests@1ed4004b]" name="feature" class="cucumber.api.testng.AbstractTestNGCucumberTests"/>
      </group> <!-- cucumber -->
    </groups>
    <test name="post_initial_extract_test" duration-ms="1499" started-at="2018-01-07T17:11:09Z" finished-at="2018-01-07T17:11:11Z">
      <class name="cod.extract.test.scripts.DBTests">
        <test-method status="PASS" signature="setUpClass()[pri:0, instance:cod.extract.test.scripts.DBTests@1ed4004b]" name="setUpClass" is-config="true" duration-ms="366" started-at="2018-01-07T17:11:09Z" finished-at="2018-01-07T17:11:09Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpClass -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:cod.extract.test.scripts.DBTests@1ed4004b]" name="setUp" is-config="true" duration-ms="303" started-at="2018-01-07T17:11:09Z" finished-at="2018-01-07T17:11:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="feature(cucumber.api.testng.CucumberFeatureWrapper)[pri:0, instance:cod.extract.test.scripts.DBTests@1ed4004b]" name="feature" duration-ms="538" started-at="2018-01-07T17:11:10Z" description="Runs Cucumber Feature" data-provider="features" finished-at="2018-01-07T17:11:10Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Organisation Extract_Load DB test feature]]>
              </value>
            </param>
          </params>
          <exception class="cucumber.runtime.CucumberException">
            <message>
              <![CDATA[java.lang.AssertionError: Expected organisation records of type 1337 but none found expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[cucumber.runtime.CucumberException: java.lang.AssertionError: Expected organisation records of type 1337 but none found expected [true] but found [false]
	at cucumber.api.testng.TestNGCucumberRunner.runCucumber(TestNGCucumberRunner.java:69)
	at cucumber.api.testng.AbstractTestNGCucumberTests.feature(AbstractTestNGCucumberTests.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.AssertionError: Expected organisation records of type 1337 but none found expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at stepdefinition.DBTest.the_database_contains_record_types(DBTest.java:75)
	at âœ½.Then the database contains "Pharmacy-YP" record types(src/test/java/features/DBTest.feature:28)
]]>
            </full-stacktrace>
          </exception> <!-- cucumber.runtime.CucumberException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- feature -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:cod.extract.test.scripts.DBTests@1ed4004b]" name="tearDown" is-config="true" duration-ms="5" started-at="2018-01-07T17:11:10Z" finished-at="2018-01-07T17:11:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="tearDownClass()[pri:0, instance:cod.extract.test.scripts.DBTests@1ed4004b]" name="tearDownClass" is-config="true" duration-ms="22" started-at="2018-01-07T17:11:10Z" finished-at="2018-01-07T17:11:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownClass -->
      </class> <!-- cod.extract.test.scripts.DBTests -->
    </test> <!-- post_initial_extract_test -->
  </suite> <!-- cod_extract_test -->
</testng-results>
